version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/library
      - JWT_SECRET=your_jwt_secret_key
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=your_secure_password
    volumes:
      - ./uploads:/app/uploads:rw
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=library
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 